# minifurkan - Dark Cyan Theme (minicyan based)

background            #0a2a2a
foreground            #d0d0d0
cursor                #d0d0d0

selection_foreground  #d0d0d0
selection_background  #324747

# Siyah (Arka plandan biraz daha açık)
color0  #0a2a2a
color8  #324747

# Kırmızı (base08 - ebcd91 yerine daha 'red' bir ton veya base0C/E tercih edilebilir, ama uyum için base08 bazlı)
color1  #ebcd91
color9  #ebcd91

# Yeşil (base0B - Senin meşhur açık yeşilin)
color2  #82e3ba
color10 #82e3ba

# Sarı (base09)
color3  #9f8340
color11 #9f8340

# Mavi (base0D)
color4  #a9d4ff
color12 #a9d4ff

# Magenta (base0E)
color5  #ffb9e5
color13 #ffb9e5

# Cyan (base0A - Senin ana aksan rengin)
color6  #209870
color14 #209870

# Beyaz/Gri (base05 ve base07)
color7  #d0d0d0
color15 #fcfcfc
