-- Made with 'mini.colors' module of https://nvim-mini.org/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "minigreen"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.documentation", { link = "@comment" })
hi(0, "@comment.error", { link = "@text.danger" })
hi(0, "@comment.note", { link = "@text.note" })
hi(0, "@comment.todo", { link = "@text.todo" })
hi(0, "@comment.warning", { link = "@text.warning" })
hi(0, "@conditional", { link = "Conditional" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@debug", { link = "Debug" })
hi(0, "@define", { link = "Define" })
hi(0, "@diff.delta", { link = "diffChanged" })
hi(0, "@diff.minus", { link = "diffRemoved" })
hi(0, "@diff.plus", { link = "diffAdded" })
hi(0, "@exception", { link = "Exception" })
hi(0, "@field", { link = "Identifier" })
hi(0, "@float", { link = "Float" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@function.call", { link = "Function" })
hi(0, "@function.macro", { link = "Macro" })
hi(0, "@function.method", { link = "@method" })
hi(0, "@function.method.call", { link = "@method.call" })
hi(0, "@include", { link = "Include" })
hi(0, "@keyword.conditional", { link = "@keyword" })
hi(0, "@keyword.conditional.ternary", { link = "Keyword" })
hi(0, "@keyword.coroutine", { link = "@keyword" })
hi(0, "@keyword.debug", { bold = true, fg = "#8ed8c4" })
hi(0, "@keyword.directive", { bold = true, fg = "#aec7fc" })
hi(0, "@keyword.directive.define", { link = "@keyword.directive" })
hi(0, "@keyword.exception", { link = "@keyword" })
hi(0, "@keyword.function", { link = "@keyword" })
hi(0, "@keyword.import", { bold = true, fg = "#aec7fc" })
hi(0, "@keyword.operator", { link = "@keyword" })
hi(0, "@keyword.repeat", { link = "@keyword" })
hi(0, "@keyword.return", { bold = true, fg = "#f5b6a0" })
hi(0, "@keyword.storage", { bold = true, fg = "#c0c9c9" })
hi(0, "@lsp.mod.deprecated", { fg = "#f2b2c9" })
hi(0, "@lsp.type.class", { link = "@structure" })
hi(0, "@lsp.type.decorator", { link = "@function" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.macro", { link = "@macro" })
hi(0, "@lsp.type.method", { link = "@method" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.struct", { link = "@structure" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", { link = "@variable" })
hi(0, "@macro", { link = "Macro" })
hi(0, "@markup.environment", { link = "@module" })
hi(0, "@markup.heading", { link = "@text.title" })
hi(0, "@markup.heading.1", { fg = "#f5b6a0" })
hi(0, "@markup.heading.1.delimiter.vimdoc", { bold = true, fg = "#435c5d" })
hi(0, "@markup.heading.2", { fg = "#dfc48b" })
hi(0, "@markup.heading.2.delimiter.vimdoc", { bold = true, fg = "#435c5d" })
hi(0, "@markup.heading.3", { fg = "#b5d29b" })
hi(0, "@markup.heading.4", { fg = "#8ed8c4" })
hi(0, "@markup.heading.4.vimdoc", { link = "Title" })
hi(0, "@markup.heading.5", { fg = "#8ad4eb" })
hi(0, "@markup.heading.6", { fg = "#aec7fc" })
hi(0, "@markup.italic", { link = "@text.emphasis" })
hi(0, "@markup.link", { link = "@text.reference" })
hi(0, "@markup.link.label", { link = "@markup.link" })
hi(0, "@markup.link.url", { fg = "#c0c9c9", underline = true })
hi(0, "@markup.list", { link = "@punctuation.special" })
hi(0, "@markup.list.checked", { link = "DiagnosticOk" })
hi(0, "@markup.list.unchecked", { link = "DiagnosticWarn" })
hi(0, "@markup.math", { link = "@string.special" })
hi(0, "@markup.quote", { link = "@string.special" })
hi(0, "@markup.raw", { link = "@text.literal" })
hi(0, "@markup.raw.block", { link = "@markup.raw" })
hi(0, "@markup.strikethrough", { link = "@text.strike" })
hi(0, "@markup.strong", { link = "@text.strong" })
hi(0, "@markup.underline", { link = "@text.underline" })
hi(0, "@method", { link = "Function" })
hi(0, "@method.call", { link = "Function" })
hi(0, "@module", { link = "@namespace" })
hi(0, "@module.builtin", { link = "@variable.builtin" })
hi(0, "@namespace", { link = "Identifier" })
hi(0, "@number.float", { link = "@float" })
hi(0, "@parameter", { fg = "#aec7fc" })
hi(0, "@preproc", { link = "PreProc" })
hi(0, "@punctuation.bracket", { link = "@punctuation" })
hi(0, "@punctuation.delimiter", { link = "@punctuation" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@repeat", { link = "Repeat" })
hi(0, "@storageclass", { link = "StorageClass" })
hi(0, "@string.documentation", { link = "@string" })
hi(0, "@string.escape", { link = "SpecialChar" })
hi(0, "@string.regexp", { link = "SpecialChar" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.path", { link = "Directory" })
hi(0, "@string.special.symbol", { link = "@constant" })
hi(0, "@string.special.url", { link = "@markup.link.url" })
hi(0, "@string.special.vimdoc", { link = "@constant" })
hi(0, "@structure", { link = "Structure" })
hi(0, "@symbol", { link = "Keyword" })
hi(0, "@tag.attribute", { link = "@tag" })
hi(0, "@tag.delimiter", { link = "@punctuation" })
hi(0, "@text.danger", { link = "ErrorMsg" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.literal", { link = "Special" })
hi(0, "@text.note", { link = "MoreMsg" })
hi(0, "@text.reference", { link = "Identifier" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.todo", { link = "Todo" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.uri", { link = "Underlined" })
hi(0, "@text.warning", { link = "WarningMsg" })
hi(0, "@type.builtin", { link = "Special" })
hi(0, "@type.definition", { link = "Typedef" })
hi(0, "@type.qualifier", { link = "StorageClass" })
hi(0, "@variable", { fg = "#c0c9c9" })
hi(0, "@variable.builtin", { link = "Special" })
hi(0, "@variable.member", { link = "@field" })
hi(0, "@variable.parameter", { link = "@parameter" })
hi(0, "Added", { fg = "#b5d29b" })
hi(0, "Beacon", { bg = "#e5eeee" })
hi(0, "Bold", { bold = true })
hi(0, "BqfPreviewFloat", { link = "NormalFloat" })
hi(0, "BqfPreviewTitle", { link = "FloatTitle" })
hi(0, "BqfSign", { fg = "#8ed8c4" })
hi(0, "BufferCurrent", { bg = "#0f2728", bold = true, fg = "#86d7db" })
hi(0, "BufferCurrentIcon", { bg = "#0f2728" })
hi(0, "BufferCurrentIndex", { link = "BufferCurrentIcon" })
hi(0, "BufferCurrentMod", { bg = "#294142", bold = true, fg = "#86d7db" })
hi(0, "BufferCurrentSign", { link = "BufferCurrent" })
hi(0, "BufferCurrentTarget", { bg = "#435c5d", bold = true, fg = "#86d7db" })
hi(0, "BufferInactive", { bg = "#031b1c", fg = "#c0c9c9" })
hi(0, "BufferInactiveIcon", { bg = "#031b1c" })
hi(0, "BufferInactiveIndex", { link = "BufferInactiveIcon" })
hi(0, "BufferInactiveMod", { bg = "#294142", fg = "#c0c9c9" })
hi(0, "BufferInactiveSign", { link = "BufferInactive" })
hi(0, "BufferInactiveTarget", { bg = "#435c5d", fg = "#c0c9c9" })
hi(0, "BufferLineBuffer", { fg = "#868e8e" })
hi(0, "BufferLineBufferSelected", { bold = true, fg = "#c0c9c9" })
hi(0, "BufferLineBufferVisible", { fg = "#c0c9c9" })
hi(0, "BufferLineCloseButton", { link = "BufferLineBackground" })
hi(0, "BufferLineCloseButtonSelected", { link = "BufferLineBufferSelected" })
hi(0, "BufferLineCloseButtonVisible", { link = "BufferLineBufferVisible" })
hi(0, "BufferLineFill", { link = "Normal" })
hi(0, "BufferLineTab", { bg = "#b5d29b", fg = "#0f2728" })
hi(0, "BufferLineTabSelected", { bg = "#b5d29b", bold = true, fg = "#0f2728" })
hi(0, "BufferOffset", { link = "Normal" })
hi(0, "BufferTabpageFill", { link = "Normal" })
hi(0, "BufferTabpages", { bg = "#b5d29b", bold = true, fg = "#0f2728" })
hi(0, "BufferVisible", { bg = "#0f2728", bold = true, fg = "#c0c9c9" })
hi(0, "BufferVisibleIcon", { bg = "#0f2728" })
hi(0, "BufferVisibleIndex", { link = "BufferVisibleIcon" })
hi(0, "BufferVisibleMod", { bg = "#294142", bold = true, fg = "#c0c9c9" })
hi(0, "BufferVisibleSign", { link = "BufferVisible" })
hi(0, "BufferVisibleTarget", { bg = "#435c5d", bold = true, fg = "#c0c9c9" })
hi(0, "Changed", { fg = "#8ed8c4" })
hi(0, "CmpItemAbbr", { fg = "#c0c9c9" })
hi(0, "CmpItemAbbrDefault", { fg = "#c0c9c9" })
hi(0, "CmpItemAbbrDeprecated", { link = "Comment" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#868e8e" })
hi(0, "CmpItemAbbrMatch", { bold = true })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#c0c9c9" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#c0c9c9" })
hi(0, "CmpItemKind", { fg = "#c0c9c9" })
hi(0, "CmpItemKindClass", { link = "Type" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindClassIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindColor", { link = "Special" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColorIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindConstant", { link = "Constant" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstantIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindConstructor", { link = "Type" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructorIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindDefault", { fg = "#8ed8c4" })
hi(0, "CmpItemKindEnum", { link = "Structure" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindEnumMember", { link = "Structure" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMemberIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindEvent", { link = "Exception" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEventIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindField", { link = "Structure" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFieldIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindFile", { link = "Tag" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFileIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindFolder", { link = "Directory" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolderIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunctionIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindIconDefault", { fg = "#8ed8c4" })
hi(0, "CmpItemKindInterface", { link = "Structure" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterfaceIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindKeyword", { link = "Keyword" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeywordIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindMethod", { link = "Function" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethodIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindModule", { link = "Structure" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModuleIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindOperator", { link = "Operator" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperatorIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindProperty", { link = "Structure" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindPropertyIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindReference", { link = "Tag" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReferenceIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindSnippet", { link = "Special" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippetIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindStruct", { link = "Structure" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStructIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindText", { link = "Normal" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTextIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindTypeParameter", { link = "Type" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameterIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindUnit", { link = "Special" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnitIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindValue", { link = "Identifier" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValueIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemKindVariable", { link = "Delimiter" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariableIconDefault", { link = "CmpItemKindIcon" })
hi(0, "CmpItemMenu", { fg = "#c0c9c9" })
hi(0, "CmpItemMenuDefault", { fg = "#c0c9c9" })
hi(0, "CocCodeLens", { link = "LspCodeLens" })
hi(0, "CocDisabled", { link = "Comment" })
hi(0, "CocFadeOut", { link = "Comment" })
hi(0, "CocMarkdownLink", { fg = "#aec7fc" })
hi(0, "CocMenuSel", { bg = "#435c5d" })
hi(0, "CocNotificationProgress", { link = "CocMarkdownLink" })
hi(0, "CocPumVirtualText", { link = "CocMarkdownLink" })
hi(0, "CocSearch", { fg = "#aec7fc" })
hi(0, "CocSelectedText", { fg = "#dfc48b" })
hi(0, "ColorColumn", { bg = "#435c5d" })
hi(0, "Comment", { fg = "#868e8e" })
hi(0, "Conceal", { fg = "#8ad4eb" })
hi(0, "Constant", { fg = "#d7b9ee" })
hi(0, "CurSearch", { bg = "#dfc48b", fg = "#0f2728" })
hi(0, "Cursor", { bg = "#c0c9c9", fg = "#0f2728" })
hi(0, "CursorColumn", { bg = "#294142" })
hi(0, "CursorLine", { bg = "#294142" })
hi(0, "CursorLineFold", { fg = "#435c5d" })
hi(0, "CursorLineNr", { bold = true, fg = "#86d7db" })
hi(0, "CursorLineSign", { fg = "#435c5d" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#b5d29b" })
hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
hi(0, "DapUIBreakpointsInfo", { link = "DiagnosticInfo" })
hi(0, "DapUIBreakpointsPath", { link = "Directory" })
hi(0, "DapUIDecoration", { link = "Title" })
hi(0, "DapUIFloatBorder", { link = "SpecialChar" })
hi(0, "DapUILineNumber", { link = "Title" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#f5b6a0" })
hi(0, "DapUIScope", { link = "Title" })
hi(0, "DapUISource", { link = "Directory" })
hi(0, "DapUIStoppedThread", { link = "Title" })
hi(0, "DapUIThread", { link = "String" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIWatchesEmpty", { link = "ErrorMsg" })
hi(0, "DapUIWatchesError", { link = "DiagnosticError" })
hi(0, "DapUIWatchesValue", { link = "String" })
hi(0, "DashboardCenter", { link = "Delimiter" })
hi(0, "DashboardFooter", { link = "Comment" })
hi(0, "DashboardHeader", { link = "Title" })
hi(0, "DashboardShortcut", { link = "WarningMsg" })
hi(0, "Definitions", { fg = "#b5d29b" })
hi(0, "DefinitionsIcon", { fg = "#8ad4eb" })
hi(0, "Delimiter", { fg = "#f5b6a0" })
hi(0, "DiagnosticDeprecated", { sp = "#f2b2c9", strikethrough = true })
hi(0, "DiagnosticError", { fg = "#f2b2c9" })
hi(0, "DiagnosticFloatingError", { bg = "#031b1c", fg = "#f2b2c9" })
hi(0, "DiagnosticFloatingHint", { bg = "#031b1c", fg = "#8ed8c4" })
hi(0, "DiagnosticFloatingInfo", { bg = "#031b1c", fg = "#aec7fc" })
hi(0, "DiagnosticFloatingOk", { bg = "#031b1c", fg = "#b5d29b" })
hi(0, "DiagnosticFloatingWarn", { bg = "#031b1c", fg = "#dfc48b" })
hi(0, "DiagnosticHint", { fg = "#8ed8c4" })
hi(0, "DiagnosticInfo", { fg = "#aec7fc" })
hi(0, "DiagnosticOk", { fg = "#b5d29b" })
hi(0, "DiagnosticUnderlineError", { sp = "#f2b2c9", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#8ed8c4", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#aec7fc", underline = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#b5d29b", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#dfc48b", underline = true })
hi(0, "DiagnosticWarn", { fg = "#dfc48b" })
hi(0, "DiffAdd", { bg = "#1c3000" })
hi(0, "DiffChange", { bg = "#00473b" })
hi(0, "DiffDelete", { bg = "#3e0d24" })
hi(0, "DiffText", { bg = "#473400" })
hi(0, "DiffTextAdd", { link = "DiffAdd" })
hi(0, "Directory", { fg = "#8ad4eb" })
hi(0, "DropBarMenuHoverIcon", { reverse = true })
hi(0, "DropBarMenuHoverSymbol", { bold = true })
hi(0, "EndOfBuffer", { fg = "#435c5d" })
hi(0, "Error", { bg = "#3e0d24" })
hi(0, "ErrorMsg", { fg = "#f2b2c9" })
hi(0, "FinderParam", { fg = "#dfc48b" })
hi(0, "FinderSpinner", { fg = "#b5d29b" })
hi(0, "FinderSpinnerBorder", { fg = "#86d7db" })
hi(0, "FinderSpinnerTitle", { link = "Title" })
hi(0, "FinderVirtText", { fg = "#f5b6a0" })
hi(0, "Float", { link = "Constant" })
hi(0, "FloatBorder", { bg = "#031b1c", fg = "#86d7db" })
hi(0, "FloatTitle", { bg = "#031b1c", bold = true, fg = "#86d7db" })
hi(0, "FoldColumn", { fg = "#435c5d" })
hi(0, "Folded", { bg = "#031b1c", fg = "#868e8e" })
hi(0, "Function", { fg = "#8ad4eb" })
hi(0, "FzfLuaBufFlagAlt", { link = "Special" })
hi(0, "FzfLuaBufFlagCur", { link = "CursorLineNr" })
hi(0, "FzfLuaBufNr", { link = "DiagnosticHint" })
hi(0, "FzfLuaHeaderBind", { link = "DiagnosticWarn" })
hi(0, "FzfLuaHeaderText", { link = "DiagnosticInfo" })
hi(0, "FzfLuaLiveSym", { link = "DiagnosticHint" })
hi(0, "FzfLuaPathColNr", { link = "DiagnosticHint" })
hi(0, "FzfLuaPathLineNr", { link = "DiagnosticInfo" })
hi(0, "FzfLuaTabMarker", { link = "DiagnosticHint" })
hi(0, "FzfLuaTabTitle", { link = "Title" })
hi(0, "FzfLuaTitle", { link = "FloatTitle" })
hi(0, "GitSignsAdd", { fg = "#b5d29b" })
hi(0, "GitSignsAddInline", { link = "GitSignsAdd" })
hi(0, "GitSignsAddLn", { link = "GitSignsAdd" })
hi(0, "GitSignsChange", { fg = "#dfc48b" })
hi(0, "GitSignsChangeInline", { link = "GitSignsChange" })
hi(0, "GitSignsChangeLn", { link = "GitSignsChange" })
hi(0, "GitSignsDelete", { fg = "#f2b2c9" })
hi(0, "GitSignsDeleteInline", { link = "GitSignsDelete" })
hi(0, "GitSignsDeleteLn", { link = "GitSignsDelete" })
hi(0, "GitSignsStagedAdd", { fg = "#5a694d" })
hi(0, "GitSignsStagedAddCul", { fg = "#5a694d" })
hi(0, "GitSignsStagedAddLn", { fg = "#5a694d" })
hi(0, "GitSignsStagedAddNr", { fg = "#5a694d" })
hi(0, "GitSignsStagedChange", { fg = "#6f6245" })
hi(0, "GitSignsStagedChangeCul", { fg = "#6f6245" })
hi(0, "GitSignsStagedChangeLn", { fg = "#6f6245" })
hi(0, "GitSignsStagedChangeNr", { fg = "#6f6245" })
hi(0, "GitSignsStagedChangedelete", { fg = "#6f6245" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#6f6245" })
hi(0, "GitSignsStagedChangedeleteLn", { fg = "#6f6245" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#6f6245" })
hi(0, "GitSignsStagedDelete", { fg = "#795964" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#795964" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#795964" })
hi(0, "GitSignsStagedTopdelete", { fg = "#795964" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#795964" })
hi(0, "GitSignsStagedTopdeleteLn", { fg = "#795964" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#795964" })
hi(0, "GitSignsStagedUntracked", { fg = "#456a75" })
hi(0, "GitSignsStagedUntrackedCul", { fg = "#5a694d" })
hi(0, "GitSignsStagedUntrackedLn", { fg = "#456a75" })
hi(0, "GitSignsStagedUntrackedNr", { fg = "#5a694d" })
hi(0, "GitSignsUntracked", { fg = "#8ad4eb" })
hi(0, "GitSignsUntrackedInline", { link = "GitSignsUntracked" })
hi(0, "GitSignsUntrackedLn", { link = "GitSignsUntracked" })
hi(0, "HelpviewCode", { bg = "#031b1c" })
hi(0, "HelpviewCodeLanguage", { bg = "#031b1c" })
hi(0, "HelpviewHeading1", { link = "@markup.heading.1" })
hi(0, "HelpviewHeading2", { link = "@markup.heading.2" })
hi(0, "HelpviewHeading3", { link = "@markup.heading.3" })
hi(0, "HelpviewHeading4", { link = "@markup.heading.4" })
hi(0, "HelpviewInlineCode", { bg = "#031b1c" })
hi(0, "HelpviewMentionlink", { fg = "#86d7db", underline = true })
hi(0, "HelpviewOptionlink", { fg = "#dfc48b", underline = true })
hi(0, "HelpviewTaglink", { bold = true, fg = "#86d7db" })
hi(0, "HelpviewTitle", { link = "Title" })
hi(0, "HopNextKey", { bold = true, fg = "#b5d29b", nocombine = true })
hi(0, "HopNextKey1", { bold = true, fg = "#f5b6a0", nocombine = true })
hi(0, "HopNextKey2", { bold = true, fg = "#a3acac", nocombine = true })
hi(0, "HopPreview", { bold = true, fg = "#dfc48b", nocombine = true })
hi(0, "HopUnmatched", { fg = "#435c5d" })
hi(0, "HydraAmaranth", { fg = "#d7b9ee" })
hi(0, "HydraBlue", { fg = "#8ad4eb" })
hi(0, "HydraHint", { link = "NormalFloat" })
hi(0, "HydraPink", { fg = "#f5b6a0" })
hi(0, "HydraRed", { fg = "#f2b2c9" })
hi(0, "HydraTeal", { fg = "#8ed8c4" })
hi(0, "Identifier", { fg = "#dfc48b" })
hi(0, "Ignore", {})
hi(0, "IncSearch", { bg = "#dfc48b", fg = "#0f2728" })
hi(0, "IndentBlanklineChar", { fg = "#435c5d", nocombine = true })
hi(0, "IndentBlanklineContextChar", { fg = "#86d7db", nocombine = true })
hi(0, "IndentBlanklineContextStart", { nocombine = true, sp = "#86d7db", underline = true })
hi(0, "IndentBlanklineIndent1", { fg = "#aec7fc", nocombine = true })
hi(0, "IndentBlanklineIndent2", { fg = "#8ed8c4", nocombine = true })
hi(0, "IndentBlanklineIndent3", { fg = "#dfc48b", nocombine = true })
hi(0, "IndentBlanklineIndent4", { fg = "#f2b2c9", nocombine = true })
hi(0, "IndentBlanklineIndent5", { fg = "#8ad4eb", nocombine = true })
hi(0, "IndentBlanklineIndent6", { fg = "#b5d29b", nocombine = true })
hi(0, "IndentBlanklineIndent7", { fg = "#f5b6a0", nocombine = true })
hi(0, "IndentBlanklineIndent8", { fg = "#d7b9ee", nocombine = true })
hi(0, "Italic", { italic = true })
hi(0, "LSOutlinePreviewBorder", { fg = "#86d7db" })
hi(0, "LazyButton", { bg = "#294142" })
hi(0, "LazyButtonActive", { bg = "#435c5d" })
hi(0, "LazyDimmed", { link = "Comment" })
hi(0, "LazyH1", { bg = "#435c5d", bold = true, fg = "#86d7db" })
hi(0, "LeapBackdrop", { link = "Comment" })
hi(0, "LeapLabel", { bold = true, fg = "#dfc48b", nocombine = true })
hi(0, "LeapLabelSelected", { bold = true, fg = "#8ed8c4", nocombine = true })
hi(0, "LeapMatch", { bold = true, fg = "#b5d29b", nocombine = true, underline = true })
hi(0, "LineNr", { fg = "#435c5d" })
hi(0, "LspCodeLens", { link = "Comment" })
hi(0, "LspCodeLensSeparator", { link = "Comment" })
hi(0, "LspReferenceText", { bg = "#435c5d" })
hi(0, "LspSagaAutoPreview", { fg = "#aec7fc" })
hi(0, "LspSagaBorderTitle", { link = "FloatTitle" })
hi(0, "LspSagaCodeActionBorder", { fg = "#86d7db" })
hi(0, "LspSagaCodeActionContent", { fg = "#c0c9c9" })
hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#8ad4eb" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#86d7db" })
hi(0, "LspSagaDiagnosticBorder", { fg = "#86d7db" })
hi(0, "LspSagaDiagnosticHeader", { link = "Title" })
hi(0, "LspSagaDiagnosticSource", { fg = "#f5b6a0" })
hi(0, "LspSagaFinderSelection", { fg = "#8ed8c4" })
hi(0, "LspSagaHoverBorder", { fg = "#86d7db" })
hi(0, "LspSagaLspFinderBorder", { fg = "#86d7db" })
hi(0, "LspSagaRenameBorder", { fg = "#86d7db" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#86d7db" })
hi(0, "LspSignatureActiveParameter", { link = "LspReferenceText" })
hi(0, "MarkviewPalette0", { bg = "#0f2728", fg = "#86d7db" })
hi(0, "MarkviewPalette0Bg", { bg = "#0f2728" })
hi(0, "MarkviewPalette0Fg", { fg = "#86d7db" })
hi(0, "MarkviewPalette0Sign", { fg = "#86d7db" })
hi(0, "MarkviewPalette1", { bg = "#3e0d24", fg = "#f2b2c9" })
hi(0, "MarkviewPalette1Bg", { bg = "#3e0d24" })
hi(0, "MarkviewPalette1Fg", { fg = "#f2b2c9" })
hi(0, "MarkviewPalette1Sign", { fg = "#f2b2c9" })
hi(0, "MarkviewPalette2", { bg = "#411000", fg = "#f5b6a0" })
hi(0, "MarkviewPalette2Bg", { bg = "#411000" })
hi(0, "MarkviewPalette2Fg", { fg = "#f5b6a0" })
hi(0, "MarkviewPalette2Sign", { fg = "#f5b6a0" })
hi(0, "MarkviewPalette3", { bg = "#473400", fg = "#dfc48b" })
hi(0, "MarkviewPalette3Bg", { bg = "#473400" })
hi(0, "MarkviewPalette3Fg", { fg = "#dfc48b" })
hi(0, "MarkviewPalette3Sign", { fg = "#dfc48b" })
hi(0, "MarkviewPalette4", { bg = "#1c3000", fg = "#b5d29b" })
hi(0, "MarkviewPalette4Bg", { bg = "#1c3000" })
hi(0, "MarkviewPalette4Fg", { fg = "#b5d29b" })
hi(0, "MarkviewPalette4Sign", { fg = "#b5d29b" })
hi(0, "MarkviewPalette5", { bg = "#00473b", fg = "#8ed8c4" })
hi(0, "MarkviewPalette5Bg", { bg = "#00473b" })
hi(0, "MarkviewPalette5Fg", { fg = "#8ed8c4" })
hi(0, "MarkviewPalette5Sign", { fg = "#8ed8c4" })
hi(0, "MarkviewPalette6", { bg = "#004354", fg = "#8ad4eb" })
hi(0, "MarkviewPalette6Bg", { bg = "#004354" })
hi(0, "MarkviewPalette6Fg", { fg = "#8ad4eb" })
hi(0, "MarkviewPalette6Sign", { fg = "#8ad4eb" })
hi(0, "MarkviewPalette7", { bg = "#101f48", fg = "#aec7fc" })
hi(0, "MarkviewPalette7Bg", { bg = "#101f48" })
hi(0, "MarkviewPalette7Fg", { fg = "#aec7fc" })
hi(0, "MarkviewPalette7Sign", { fg = "#aec7fc" })
hi(0, "MasonError", { fg = "#f2b2c9" })
hi(0, "MasonHeader", { bg = "#8ad4eb", bold = true, fg = "#0f2728" })
hi(0, "MasonHeaderSecondary", { bg = "#aec7fc", bold = true, fg = "#0f2728" })
hi(0, "MasonHeading", { link = "Bold" })
hi(0, "MasonHighlight", { fg = "#86d7db" })
hi(0, "MasonHighlightBlock", { bg = "#86d7db", fg = "#0f2728" })
hi(0, "MasonHighlightBlockBold", { link = "MasonHeaderSecondary" })
hi(0, "MasonHighlightBlockBoldSecondary", { link = "MasonHeader" })
hi(0, "MasonHighlightBlockSecondary", { bg = "#8ad4eb", fg = "#0f2728" })
hi(0, "MasonHighlightSecondary", { fg = "#8ad4eb" })
hi(0, "MasonLink", { link = "MasonHighlight" })
hi(0, "MasonMuted", { link = "Comment" })
hi(0, "MasonMutedBlock", { bg = "#435c5d", fg = "#0f2728" })
hi(0, "MasonMutedBlockBold", { bg = "#435c5d", bold = true, fg = "#0f2728" })
hi(0, "MatchParen", { bg = "#435c5d", bold = true })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "FloatBorder" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { link = "FloatTitle" })
hi(0, "MiniCmdlinePeekBorder", { link = "FloatBorder" })
hi(0, "MiniCmdlinePeekLineNr", { link = "DiagnosticSignWarn" })
hi(0, "MiniCmdlinePeekNormal", { link = "NormalFloat" })
hi(0, "MiniCmdlinePeekSep", { link = "SignColumn" })
hi(0, "MiniCmdlinePeekSign", { link = "DiagnosticSignHint" })
hi(0, "MiniCmdlinePeekTitle", { link = "FloatTitle" })
hi(0, "MiniCompletionActiveParameter", { link = "LspSignatureActiveParameter" })
hi(0, "MiniCompletionDeprecated", { link = "DiagnosticDeprecated" })
hi(0, "MiniCompletionInfoBorderOutdated", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniDepsChangeAdded", { link = "diffAdded" })
hi(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
hi(0, "MiniDepsHint", { link = "DiagnosticHint" })
hi(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
hi(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
hi(0, "MiniDepsPlaceholder", { link = "Comment" })
hi(0, "MiniDepsTitle", { link = "Title" })
hi(0, "MiniDepsTitleError", { link = "DiffDelete" })
hi(0, "MiniDepsTitleSame", { link = "DiffText" })
hi(0, "MiniDepsTitleUpdate", { link = "DiffAdd" })
hi(0, "MiniDiffSignAdd", { link = "diffAdded" })
hi(0, "MiniDiffSignChange", { link = "diffChanged" })
hi(0, "MiniDiffSignDelete", { link = "diffRemoved" })
hi(0, "MiniFilesFile", { fg = "#c0c9c9" })
hi(0, "MiniFilesTitleFocused", { bg = "#031b1c", bold = true, fg = "#c0c9c9" })
hi(0, "MiniHipatternsFixme", { bg = "#f2b2c9", bold = true, fg = "#0f2728" })
hi(0, "MiniHipatternsHack", { bg = "#dfc48b", bold = true, fg = "#0f2728" })
hi(0, "MiniHipatternsNote", { bg = "#8ed8c4", bold = true, fg = "#0f2728" })
hi(0, "MiniHipatternsTodo", { bg = "#aec7fc", bold = true, fg = "#0f2728" })
hi(0, "MiniIconsAzure", { fg = "#8ad4eb" })
hi(0, "MiniIconsBlue", { fg = "#aec7fc" })
hi(0, "MiniIconsCyan", { fg = "#8ed8c4" })
hi(0, "MiniIconsGreen", { fg = "#b5d29b" })
hi(0, "MiniIconsGrey", { fg = "#d2dbdb" })
hi(0, "MiniIconsOrange", { fg = "#f5b6a0" })
hi(0, "MiniIconsPurple", { fg = "#d7b9ee" })
hi(0, "MiniIconsRed", { fg = "#f2b2c9" })
hi(0, "MiniIconsYellow", { fg = "#dfc48b" })
hi(0, "MiniIndentscopeSymbol", { fg = "#86d7db" })
hi(0, "MiniIndentscopeSymbolOff", { fg = "#f2b2c9" })
hi(0, "MiniJump", { sp = "#86d7db", undercurl = true })
hi(0, "MiniJump2dDim", { fg = "#435c5d" })
hi(0, "MiniJump2dSpot", { bg = "#001314", bold = true, fg = "#e5eeee", nocombine = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#001314", fg = "#d2dbdb", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { link = "MiniJump2dSpot" })
hi(0, "MiniMapNormal", { bg = "#031b1c", fg = "#868e8e" })
hi(0, "MiniMapSymbolCount", { fg = "#868e8e" })
hi(0, "MiniMapSymbolLine", { fg = "#86d7db" })
hi(0, "MiniMapSymbolView", { fg = "#86d7db" })
hi(0, "MiniNotifyBorder", { link = "FloatBorder" })
hi(0, "MiniNotifyLspProgress", { link = "MiniNotifyNormal" })
hi(0, "MiniNotifyNormal", { link = "NormalFloat" })
hi(0, "MiniNotifyTitle", { link = "FloatTitle" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniPickBorder", { link = "FloatBorder" })
hi(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniPickBorderText", { link = "FloatTitle" })
hi(0, "MiniPickCursor", { blend = 100, nocombine = true })
hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickIconDirectory", { link = "Directory" })
hi(0, "MiniPickIconFile", { link = "MiniPickNormal" })
hi(0, "MiniPickMatchCurrent", { link = "CursorLine" })
hi(0, "MiniPickMatchMarked", { link = "Visual" })
hi(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickNormal", { link = "NormalFloat" })
hi(0, "MiniPickPreviewLine", { link = "CursorLine" })
hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
hi(0, "MiniPickPrompt", { link = "MiniPickMatchRanges" })
hi(0, "MiniPickPromptCaret", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniPickPromptPrefix", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniSnippetsCurrent", { sp = "#dfc48b", underdouble = true })
hi(0, "MiniSnippetsCurrentReplace", { sp = "#f2b2c9", underdouble = true })
hi(0, "MiniSnippetsFinal", { sp = "#b5d29b", underdouble = true })
hi(0, "MiniSnippetsUnvisited", { sp = "#8ed8c4", underdouble = true })
hi(0, "MiniSnippetsVisited", { sp = "#aec7fc", underdouble = true })
hi(0, "MiniStarterCurrent", { link = "MiniStarterItem" })
hi(0, "MiniStarterFooter", { link = "Comment" })
hi(0, "MiniStarterHeader", { bold = true, fg = "#86d7db" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItem", { link = "Normal" })
hi(0, "MiniStarterItemBullet", { fg = "#868e8e" })
hi(0, "MiniStarterItemPrefix", { bold = true, fg = "#dfc48b" })
hi(0, "MiniStarterQuery", { bold = true, fg = "#b5d29b" })
hi(0, "MiniStarterSection", { fg = "#d7b9ee" })
hi(0, "MiniStatuslineDevinfo", { bg = "#294142", fg = "#a3acac" })
hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
hi(0, "MiniStatuslineFilename", { bg = "#0f2728", fg = "#a3acac" })
hi(0, "MiniStatuslineInactive", { link = "StatusLineNC" })
hi(0, "MiniStatuslineModeCommand", { bg = "#dfc48b", bold = true, fg = "#0f2728" })
hi(0, "MiniStatuslineModeInsert", { bg = "#8ad4eb", bold = true, fg = "#0f2728" })
hi(0, "MiniStatuslineModeNormal", { bg = "#c0c9c9", bold = true, fg = "#0f2728" })
hi(0, "MiniStatuslineModeOther", { bg = "#8ed8c4", bold = true, fg = "#0f2728" })
hi(0, "MiniStatuslineModeReplace", { bg = "#f2b2c9", bold = true, fg = "#0f2728" })
hi(0, "MiniStatuslineModeVisual", { bg = "#b5d29b", bold = true, fg = "#0f2728" })
hi(0, "MiniTablineCurrent", { bg = "#0f2728", bold = true, fg = "#86d7db" })
hi(0, "MiniTablineFill", { link = "MiniTablineHidden" })
hi(0, "MiniTablineHidden", { bg = "#031b1c", fg = "#a3acac" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#86d7db", bold = true, fg = "#0f2728" })
hi(0, "MiniTablineModifiedHidden", { bg = "#a3acac", fg = "#031b1c" })
hi(0, "MiniTablineModifiedVisible", { bg = "#a3acac", bold = true, fg = "#031b1c" })
hi(0, "MiniTablineTabpagesection", { bg = "#b5d29b", bold = true, fg = "#0f2728" })
hi(0, "MiniTablineTrunc", { bg = "#031b1c", bold = true, fg = "#86d7db" })
hi(0, "MiniTablineVisible", { bg = "#031b1c", bold = true, fg = "#a3acac" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#f2b2c9" })
hi(0, "MiniTestPass", { bold = true, fg = "#b5d29b" })
hi(0, "MiniTrailspace", { bg = "#3e0d24" })
hi(0, "ModeMsg", { fg = "#b5d29b" })
hi(0, "MoreMsg", { fg = "#8ad4eb" })
hi(0, "MsgArea", { link = "Normal" })
hi(0, "MsgSeparator", { bg = "#294142" })
hi(0, "NeoTreeDimText", { fg = "#435c5d" })
hi(0, "NeoTreeDotfile", { fg = "#a3acac" })
hi(0, "NeoTreeFadeText1", { link = "NeoTreeDimText" })
hi(0, "NeoTreeFadeText2", { fg = "#435c5d" })
hi(0, "NeoTreeGitAdded", { fg = "#b5d29b" })
hi(0, "NeoTreeGitConflict", { bold = true, fg = "#f5b6a0" })
hi(0, "NeoTreeGitDeleted", { fg = "#f2b2c9" })
hi(0, "NeoTreeGitModified", { fg = "#dfc48b" })
hi(0, "NeoTreeGitUnstaged", { fg = "#d7b9ee" })
hi(0, "NeoTreeGitUntracked", { fg = "#8ed8c4" })
hi(0, "NeoTreeMessage", { bg = "#294142", fg = "#c0c9c9" })
hi(0, "NeoTreeModified", { fg = "#d2dbdb" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#86d7db" })
hi(0, "NeoTreeTabInactive", { fg = "#868e8e" })
hi(0, "NeoTreeTabSeparatorActive", { bg = "#435c5d", fg = "#868e8e" })
hi(0, "NeoTreeTabSeparatorInactive", { bg = "#294142", fg = "#294142" })
hi(0, "NeogitCommitViewHeader", { link = "Special" })
hi(0, "NeogitDiffAdd", { link = "DiffAdd" })
hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
hi(0, "NeogitDiffDelete", { link = "DiffDelete" })
hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
hi(0, "NeogitFold", { link = "FoldColumn" })
hi(0, "NeogitHunkHeader", { fg = "#86d7db" })
hi(0, "NeogitHunkHeaderHighlight", { bold = true, fg = "#86d7db" })
hi(0, "NeogitNotificationError", { link = "DiagnosticError" })
hi(0, "NeogitNotificationInfo", { link = "DiagnosticInfo" })
hi(0, "NeogitNotificationWarning", { link = "DiagnosticWarn" })
hi(0, "NoiceCmdlinePopupBorder", { fg = "#8ad4eb" })
hi(0, "NoiceConfirmBorder", { fg = "#dfc48b" })
hi(0, "NoiceFormatProgressDone", { bg = "#86d7db", fg = "#0f2728" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NonText", { fg = "#435c5d" })
hi(0, "Normal", { bg = "#0f2728", fg = "#c0c9c9" })
hi(0, "NormalFloat", { bg = "#031b1c", fg = "#c0c9c9" })
hi(0, "NormalNC", { link = "Normal" })
hi(0, "NotifyDEBUGBorder", { fg = "#b5d29b" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyDEBUGTitle", { link = "NotifyDEBUGBorder" })
hi(0, "NotifyERRORBorder", { fg = "#f2b2c9" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORBorder" })
hi(0, "NotifyERRORTitle", { link = "NotifyERRORBorder" })
hi(0, "NotifyINFOBorder", { fg = "#aec7fc" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOBorder" })
hi(0, "NotifyINFOTitle", { link = "NotifyINFOBorder" })
hi(0, "NotifyTRACEBorder", { fg = "#8ed8c4" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACEBorder" })
hi(0, "NotifyTRACETitle", { link = "NotifyTRACEBorder" })
hi(0, "NotifyWARNBorder", { fg = "#dfc48b" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNBorder" })
hi(0, "NotifyWARNTitle", { link = "NotifyWARNBorder" })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#b5d29b" })
hi(0, "NvimTreeFolderIcon", { fg = "#868e8e" })
hi(0, "NvimTreeGitDeleted", { fg = "#f2b2c9" })
hi(0, "NvimTreeGitDirty", { fg = "#dfc48b" })
hi(0, "NvimTreeGitMerge", { fg = "#f5b6a0" })
hi(0, "NvimTreeGitNew", { fg = "#8ed8c4" })
hi(0, "NvimTreeGitRenamed", { fg = "#d7b9ee" })
hi(0, "NvimTreeGitStaged", { fg = "#b5d29b" })
hi(0, "NvimTreeImageFile", { fg = "#f5b6a0" })
hi(0, "NvimTreeIndentMarker", { link = "NvimTreeFolderIcon" })
hi(0, "NvimTreeOpenedFile", { link = "NvimTreeExecFile" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#86d7db" })
hi(0, "NvimTreeSpecialFile", { fg = "#86d7db", underline = true })
hi(0, "NvimTreeSymlink", { bold = true, fg = "#aec7fc" })
hi(0, "NvimTreeWindowPicker", { bg = "#435c5d", bold = true, fg = "#c0c9c9" })
hi(0, "OkMsg", { fg = "#b5d29b" })
hi(0, "Operator", { fg = "#c0c9c9" })
hi(0, "OutlineDetail", { fg = "#435c5d" })
hi(0, "OutlineFoldPrefix", { fg = "#dfc48b" })
hi(0, "OutlineIndentEvn", { fg = "#868e8e" })
hi(0, "OutlineIndentOdd", { fg = "#c0c9c9" })
hi(0, "Pmenu", { bg = "#294142", fg = "#c0c9c9" })
hi(0, "PmenuBorder", { link = "Pmenu" })
hi(0, "PmenuMatchSel", { blend = 0, bold = true, reverse = true })
hi(0, "PmenuThumb", { bg = "#435c5d" })
hi(0, "PounceAccept", { bg = "#dfc48b", bold = true, fg = "#0f2728", nocombine = true })
hi(0, "PounceAcceptBest", { bg = "#b5d29b", bold = true, fg = "#0f2728", nocombine = true })
hi(0, "PounceGap", { bg = "#435c5d", bold = true, fg = "#0f2728", nocombine = true })
hi(0, "PounceMatch", { bg = "#c0c9c9", bold = true, fg = "#0f2728", nocombine = true })
hi(0, "PreProc", { fg = "#aec7fc" })
hi(0, "Question", { fg = "#8ad4eb" })
hi(0, "QuickFixLine", { bold = true })
hi(0, "RainbowDelimiterBlue", { fg = "#8ad4eb" })
hi(0, "RainbowDelimiterCyan", { fg = "#8ed8c4" })
hi(0, "RainbowDelimiterGreen", { fg = "#b5d29b" })
hi(0, "RainbowDelimiterOrange", { fg = "#f5b6a0" })
hi(0, "RainbowDelimiterRed", { fg = "#f2b2c9" })
hi(0, "RainbowDelimiterViolet", { fg = "#d7b9ee" })
hi(0, "RainbowDelimiterYellow", { fg = "#dfc48b" })
hi(0, "References", { fg = "#b5d29b" })
hi(0, "ReferencesIcon", { fg = "#8ad4eb" })
hi(0, "Removed", { fg = "#f2b2c9" })
hi(0, "RenderMarkdownBullet", { fg = "#86d7db" })
hi(0, "RenderMarkdownChecked", { link = "DiagnosticOk" })
hi(0, "RenderMarkdownCode", { bg = "#031b1c" })
hi(0, "RenderMarkdownCodeInline", { bg = "#031b1c" })
hi(0, "RenderMarkdownDash", { fg = "#86d7db" })
hi(0, "RenderMarkdownH1", { fg = "#f5b6a0" })
hi(0, "RenderMarkdownH1Bg", { bg = "#411000" })
hi(0, "RenderMarkdownH2", { fg = "#dfc48b" })
hi(0, "RenderMarkdownH2Bg", { bg = "#473400" })
hi(0, "RenderMarkdownH3", { fg = "#b5d29b" })
hi(0, "RenderMarkdownH3Bg", { bg = "#1c3000" })
hi(0, "RenderMarkdownH4", { fg = "#8ed8c4" })
hi(0, "RenderMarkdownH4Bg", { bg = "#00473b" })
hi(0, "RenderMarkdownH5", { fg = "#8ad4eb" })
hi(0, "RenderMarkdownH5Bg", { bg = "#004354" })
hi(0, "RenderMarkdownH6", { fg = "#aec7fc" })
hi(0, "RenderMarkdownH6Bg", { bg = "#101f48" })
hi(0, "RenderMarkdownTodo", { link = "Todo" })
hi(0, "RenderMarkdownUnchecked", { link = "DiagnosticWarn" })
hi(0, "Search", { bg = "#86d7db", fg = "#0f2728" })
hi(0, "SignColumn", { fg = "#435c5d" })
hi(0, "SnacksPickerBufFlags", { link = "Comment" })
hi(0, "SnacksPickerDir", { link = "Comment" })
hi(0, "SnacksPickerGitStatusIgnored", { link = "Comment" })
hi(0, "SnacksPickerGitStatusUntracked", { link = "Comment" })
hi(0, "SnacksPickerKeymapRhs", { link = "Comment" })
hi(0, "SnacksPickerListCursorLine", { link = "CursorLine" })
hi(0, "SnacksPickerPathHidden", { link = "Comment" })
hi(0, "SnacksPickerPathIgnored", { link = "Comment" })
hi(0, "SnacksPickerTotals", { link = "Comment" })
hi(0, "SnacksPickerUnselected", { link = "Comment" })
hi(0, "Sneak", { bg = "#f5b6a0", fg = "#0f2728" })
hi(0, "SneakLabel", { bg = "#f5b6a0", bold = true, fg = "#0f2728" })
hi(0, "SneakScope", { bg = "#e5eeee", fg = "#0f2728" })
hi(0, "SnippetTabstop", { bg = "#473400" })
hi(0, "SnippetTabstopActive", { bg = "#1c3000" })
hi(0, "Special", { fg = "#8ed8c4" })
hi(0, "SpecialKey", { fg = "#435c5d" })
hi(0, "SpellBad", { sp = "#f2b2c9", undercurl = true })
hi(0, "SpellCap", { sp = "#8ed8c4", undercurl = true })
hi(0, "SpellLocal", { sp = "#dfc48b", undercurl = true })
hi(0, "SpellRare", { sp = "#aec7fc", undercurl = true })
hi(0, "Statement", { bold = true, fg = "#c0c9c9" })
hi(0, "StatusLine", { bg = "#0f2728", fg = "#a3acac" })
hi(0, "StatusLineNC", { bg = "#031b1c", fg = "#a3acac" })
hi(0, "StderrMsg", { link = "ErrorMsg" })
hi(0, "StdoutMsg", { link = "MsgArea" })
hi(0, "String", { fg = "#b5d29b" })
hi(0, "Substitute", { bg = "#aec7fc", fg = "#0f2728" })
hi(0, "TabLine", { bg = "#031b1c", fg = "#a3acac" })
hi(0, "TabLineSel", { bg = "#031b1c", fg = "#86d7db" })
hi(0, "TargetFileName", { fg = "#c0c9c9" })
hi(0, "TelescopeBorder", { fg = "#86d7db" })
hi(0, "TelescopeMatching", { bold = true })
hi(0, "TelescopeMultiSelection", { bg = "#435c5d" })
hi(0, "TelescopeSelection", { bg = "#294142" })
hi(0, "TermCursorNC", { reverse = true })
hi(0, "TinyInlineDiagnosticVirtualTextArrow", { bg = "#294142", fg = "#435c5d" })
hi(0, "TinyInlineDiagnosticVirtualTextArrowNoBg", { fg = "#435c5d" })
hi(0, "TinyInlineDiagnosticVirtualTextBg", { bg = "#294142" })
hi(0, "TinyInlineDiagnosticVirtualTextError", { bg = "#41464b", fg = "#f2b2c9" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorCursorLine", { bg = "#294142", fg = "#f2b2c9" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorMixError", { bg = "#41464b", fg = "#f2b2c9" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorMixHint", { bg = "#2b4e4a", fg = "#f2b2c9" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorMixInfo", { bg = "#324a57", fg = "#f2b2c9" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorMixWarn", { bg = "#3d4a3e", fg = "#f2b2c9" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorNoBg", { fg = "#f2b2c9" })
hi(0, "TinyInlineDiagnosticVirtualTextHint", { bg = "#2b4e4a", fg = "#8ed8c4" })
hi(0, "TinyInlineDiagnosticVirtualTextHintCursorLine", { bg = "#294142", fg = "#8ed8c4" })
hi(0, "TinyInlineDiagnosticVirtualTextHintMixError", { bg = "#41464b", fg = "#8ed8c4" })
hi(0, "TinyInlineDiagnosticVirtualTextHintMixHint", { bg = "#2b4e4a", fg = "#8ed8c4" })
hi(0, "TinyInlineDiagnosticVirtualTextHintMixInfo", { bg = "#324a57", fg = "#8ed8c4" })
hi(0, "TinyInlineDiagnosticVirtualTextHintMixWarn", { bg = "#3d4a3e", fg = "#8ed8c4" })
hi(0, "TinyInlineDiagnosticVirtualTextHintNoBg", { fg = "#8ed8c4" })
hi(0, "TinyInlineDiagnosticVirtualTextInfo", { bg = "#324a57", fg = "#aec7fc" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoCursorLine", { bg = "#294142", fg = "#aec7fc" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoMixError", { bg = "#41464b", fg = "#aec7fc" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoMixHint", { bg = "#2b4e4a", fg = "#aec7fc" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoMixInfo", { bg = "#324a57", fg = "#aec7fc" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoMixWarn", { bg = "#3d4a3e", fg = "#aec7fc" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoNoBg", { fg = "#aec7fc" })
hi(0, "TinyInlineDiagnosticVirtualTextWarn", { bg = "#3d4a3e", fg = "#dfc48b" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnCursorLine", { bg = "#294142", fg = "#dfc48b" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnMixError", { bg = "#41464b", fg = "#dfc48b" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnMixHint", { bg = "#2b4e4a", fg = "#dfc48b" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnMixInfo", { bg = "#324a57", fg = "#dfc48b" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnMixWarn", { bg = "#3d4a3e", fg = "#dfc48b" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnNoBg", { fg = "#dfc48b" })
hi(0, "TinyInlineInvDiagnosticVirtualTextError", { bg = "#294142", fg = "#41464b" })
hi(0, "TinyInlineInvDiagnosticVirtualTextErrorCursorLine", { bg = "#294142", fg = "#41464b" })
hi(0, "TinyInlineInvDiagnosticVirtualTextErrorNoBg", { fg = "#41464b" })
hi(0, "TinyInlineInvDiagnosticVirtualTextHint", { bg = "#294142", fg = "#2b4e4a" })
hi(0, "TinyInlineInvDiagnosticVirtualTextHintCursorLine", { bg = "#294142", fg = "#2b4e4a" })
hi(0, "TinyInlineInvDiagnosticVirtualTextHintNoBg", { fg = "#2b4e4a" })
hi(0, "TinyInlineInvDiagnosticVirtualTextInfo", { bg = "#294142", fg = "#324a57" })
hi(0, "TinyInlineInvDiagnosticVirtualTextInfoCursorLine", { bg = "#294142", fg = "#324a57" })
hi(0, "TinyInlineInvDiagnosticVirtualTextInfoNoBg", { fg = "#324a57" })
hi(0, "TinyInlineInvDiagnosticVirtualTextWarn", { bg = "#294142", fg = "#3d4a3e" })
hi(0, "TinyInlineInvDiagnosticVirtualTextWarnCursorLine", { bg = "#294142", fg = "#3d4a3e" })
hi(0, "TinyInlineInvDiagnosticVirtualTextWarnNoBg", { fg = "#3d4a3e" })
hi(0, "Title", { fg = "#86d7db" })
hi(0, "Todo", { bg = "#0f2728", bold = true, fg = "#86d7db" })
hi(0, "TodoBgFIX", { bg = "#f2b2c9", bold = true, fg = "#0f2728" })
hi(0, "TodoBgHACK", { bg = "#dfc48b", bold = true, fg = "#0f2728" })
hi(0, "TodoBgNOTE", { bg = "#8ed8c4", bold = true, fg = "#0f2728" })
hi(0, "TodoBgPERF", { bg = "#dfc48b", bold = true, fg = "#0f2728" })
hi(0, "TodoBgTEST", { bg = "#dfc48b", bold = true, fg = "#0f2728" })
hi(0, "TodoBgTODO", { bg = "#aec7fc", bold = true, fg = "#0f2728" })
hi(0, "TodoBgWARN", { bg = "#dfc48b", bold = true, fg = "#0f2728" })
hi(0, "TodoFgFIX", { fg = "#f2b2c9" })
hi(0, "TodoFgHACK", { fg = "#dfc48b" })
hi(0, "TodoFgNOTE", { fg = "#8ed8c4" })
hi(0, "TodoFgPERF", { fg = "#dfc48b" })
hi(0, "TodoFgTEST", { fg = "#dfc48b" })
hi(0, "TodoFgTODO", { fg = "#aec7fc" })
hi(0, "TodoFgWARN", { fg = "#dfc48b" })
hi(0, "TodoSignFIX", { fg = "#f2b2c9" })
hi(0, "TodoSignHACK", { fg = "#dfc48b" })
hi(0, "TodoSignNOTE", { fg = "#8ed8c4" })
hi(0, "TodoSignPERF", { fg = "#dfc48b" })
hi(0, "TodoSignTEST", { fg = "#dfc48b" })
hi(0, "TodoSignTODO", { fg = "#aec7fc" })
hi(0, "TodoSignWARN", { fg = "#dfc48b" })
hi(0, "TroubleCount", { bold = true, fg = "#86d7db" })
hi(0, "TroubleFoldIcon", { bold = true, fg = "#86d7db" })
hi(0, "TroubleIndent", { fg = "#435c5d" })
hi(0, "TroubleLocation", { fg = "#a3acac" })
hi(0, "TroubleSignError", { link = "DiagnosticError" })
hi(0, "TroubleSignHint", { link = "DiagnosticHint" })
hi(0, "TroubleSignInformation", { link = "DiagnosticInfo" })
hi(0, "TroubleSignOther", { link = "DiagnosticInfo" })
hi(0, "TroubleSignWarning", { link = "DiagnosticWarn" })
hi(0, "TroubleText", { fg = "#c0c9c9" })
hi(0, "TroubleTextError", { link = "TroubleText" })
hi(0, "TroubleTextHint", { link = "TroubleText" })
hi(0, "TroubleTextInformation", { link = "TroubleText" })
hi(0, "TroubleTextWarning", { link = "TroubleText" })
hi(0, "Type", { fg = "#c0c9c9" })
hi(0, "UfoFoldedFg", { fg = "#c0c9c9" })
hi(0, "VertSplit", { fg = "#86d7db" })
hi(0, "Visual", { bg = "#435c5d" })
hi(0, "VisualNOS", { bg = "#294142" })
hi(0, "WarningMsg", { fg = "#dfc48b" })
hi(0, "WhichKey", { fg = "#8ed8c4" })
hi(0, "WhichKeyBorder", { link = "FloatBorder" })
hi(0, "WhichKeyDesc", { fg = "#c0c9c9" })
hi(0, "WhichKeyFloat", { bg = "#031b1c", fg = "#c0c9c9" })
hi(0, "WhichKeyGroup", { fg = "#f2b2c9" })
hi(0, "WhichKeySeparator", { fg = "#b5d29b" })
hi(0, "WhichKeyValue", { link = "Comment" })
hi(0, "Whitespace", { fg = "#435c5d" })
hi(0, "WinBar", {})
hi(0, "WinBarNC", {})
hi(0, "WinSeparator", { fg = "#86d7db" })
hi(0, "diffAdded", { fg = "#b5d29b" })
hi(0, "diffChanged", { fg = "#8ed8c4" })
hi(0, "diffFile", { fg = "#dfc48b" })
hi(0, "diffLine", { fg = "#aec7fc" })
hi(0, "diffRemoved", { fg = "#f2b2c9" })
hi(0, "gitcommitBranch", { bold = true, fg = "#f5b6a0" })
hi(0, "gitcommitComment", { link = "Comment" })
hi(0, "gitcommitDiscarded", { link = "Comment" })
hi(0, "gitcommitDiscardedFile", { bold = true, fg = "#dfc48b" })
hi(0, "gitcommitDiscardedType", { fg = "#8ad4eb" })
hi(0, "gitcommitHeader", { link = "Title" })
hi(0, "gitcommitOverflow", { fg = "#dfc48b" })
hi(0, "gitcommitSelected", { link = "Comment" })
hi(0, "gitcommitSelectedFile", { bold = true, fg = "#b5d29b" })
hi(0, "gitcommitSelectedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitSummary", { fg = "#b5d29b" })
hi(0, "gitcommitUnmergedFile", { link = "gitcommitDiscardedFile" })
hi(0, "gitcommitUnmergedType", { link = "gitcommitDiscardedType" })
hi(0, "gitcommitUntracked", { link = "Comment" })
hi(0, "gitcommitUntrackedFile", { fg = "#8ed8c4" })
hi(0, "lCursor", { bg = "#c0c9c9", fg = "#0f2728" })
hi(0, "lualine_a_inactive", { bg = "#14191f", bold = true, fg = "#e6e1cf", nocombine = true })
hi(0, "lualine_a_insert", { bg = "#b8cc52", bold = true, fg = "#0f1419", nocombine = true })
hi(0, "lualine_a_normal", { bg = "#36a3d9", bold = true, fg = "#0f1419", nocombine = true })
hi(0, "lualine_a_replace", { bg = "#f07178", bold = true, fg = "#0f1419", nocombine = true })
hi(0, "lualine_a_visual", { bg = "#ffee99", bold = true, fg = "#0f1419", nocombine = true })
hi(0, "lualine_b_fancy_branch_command", { bg = "#14191f", fg = "#fc5603", nocombine = true })
hi(0, "lualine_b_fancy_branch_inactive", { bg = "#14191f", fg = "#fc5603", nocombine = true })
hi(0, "lualine_b_fancy_branch_insert", { bg = "#14191f", fg = "#fc5603", nocombine = true })
hi(0, "lualine_b_fancy_branch_normal", { bg = "#14191f", fg = "#fc5603", nocombine = true })
hi(0, "lualine_b_fancy_branch_replace", { bg = "#14191f", fg = "#fc5603", nocombine = true })
hi(0, "lualine_b_fancy_branch_terminal", { bg = "#14191f", fg = "#fc5603", nocombine = true })
hi(0, "lualine_b_fancy_branch_visual", { bg = "#14191f", fg = "#fc5603", nocombine = true })
hi(0, "lualine_b_fancy_diff_added_command", { bg = "#14191f", fg = "#b5d29b", nocombine = true })
hi(0, "lualine_b_fancy_diff_added_inactive", { bg = "#14191f", fg = "#b5d29b", nocombine = true })
hi(0, "lualine_b_fancy_diff_added_insert", { bg = "#14191f", fg = "#b5d29b", nocombine = true })
hi(0, "lualine_b_fancy_diff_added_normal", { bg = "#14191f", fg = "#b5d29b", nocombine = true })
hi(0, "lualine_b_fancy_diff_added_replace", { bg = "#14191f", fg = "#b5d29b", nocombine = true })
hi(0, "lualine_b_fancy_diff_added_terminal", { bg = "#14191f", fg = "#b5d29b", nocombine = true })
hi(0, "lualine_b_fancy_diff_added_visual", { bg = "#14191f", fg = "#b5d29b", nocombine = true })
hi(0, "lualine_b_fancy_diff_modified_command", { bg = "#14191f", fg = "#dfc48b", nocombine = true })
hi(0, "lualine_b_fancy_diff_modified_inactive", { bg = "#14191f", fg = "#dfc48b", nocombine = true })
hi(0, "lualine_b_fancy_diff_modified_insert", { bg = "#14191f", fg = "#dfc48b", nocombine = true })
hi(0, "lualine_b_fancy_diff_modified_normal", { bg = "#14191f", fg = "#dfc48b", nocombine = true })
hi(0, "lualine_b_fancy_diff_modified_replace", { bg = "#14191f", fg = "#dfc48b", nocombine = true })
hi(0, "lualine_b_fancy_diff_modified_terminal", { bg = "#14191f", fg = "#dfc48b", nocombine = true })
hi(0, "lualine_b_fancy_diff_modified_visual", { bg = "#14191f", fg = "#dfc48b", nocombine = true })
hi(0, "lualine_b_fancy_diff_removed_command", { bg = "#14191f", fg = "#f2b2c9", nocombine = true })
hi(0, "lualine_b_fancy_diff_removed_inactive", { bg = "#14191f", fg = "#f2b2c9", nocombine = true })
hi(0, "lualine_b_fancy_diff_removed_insert", { bg = "#14191f", fg = "#f2b2c9", nocombine = true })
hi(0, "lualine_b_fancy_diff_removed_normal", { bg = "#14191f", fg = "#f2b2c9", nocombine = true })
hi(0, "lualine_b_fancy_diff_removed_replace", { bg = "#14191f", fg = "#f2b2c9", nocombine = true })
hi(0, "lualine_b_fancy_diff_removed_terminal", { bg = "#14191f", fg = "#f2b2c9", nocombine = true })
hi(0, "lualine_b_fancy_diff_removed_visual", { bg = "#14191f", fg = "#f2b2c9", nocombine = true })
hi(0, "lualine_b_inactive", { bg = "#14191f", fg = "#e6e1cf", nocombine = true })
hi(0, "lualine_b_insert", { bg = "#14191f", fg = "#e6e1cf", nocombine = true })
hi(0, "lualine_b_normal", { bg = "#14191f", fg = "#e6e1cf", nocombine = true })
hi(0, "lualine_b_replace", { bg = "#14191f", fg = "#e6e1cf", nocombine = true })
hi(0, "lualine_b_visual", { bg = "#14191f", fg = "#e6e1cf", nocombine = true })
hi(0, "lualine_c_inactive", { bg = "#0f1419", fg = "#e6e1cf", nocombine = true })
hi(0, "lualine_c_normal", { bg = "#0f1419", fg = "#3e4b59", nocombine = true })
hi(0, "lualine_transparent", { bg = "#0f2728", fg = "#c0c9c9", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_error_command", { bg = "#0f1419", fg = "#f2b2c9", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_error_inactive", { bg = "#0f1419", fg = "#f2b2c9", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_error_insert", { bg = "#0f1419", fg = "#f2b2c9", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_error_normal", { bg = "#0f1419", fg = "#f2b2c9", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_error_replace", { bg = "#0f1419", fg = "#f2b2c9", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_error_terminal", { bg = "#0f1419", fg = "#f2b2c9", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_error_visual", { bg = "#0f1419", fg = "#f2b2c9", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_hint_command", { bg = "#0f1419", fg = "#8ed8c4", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_hint_inactive", { bg = "#0f1419", fg = "#8ed8c4", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_hint_insert", { bg = "#0f1419", fg = "#8ed8c4", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_hint_normal", { bg = "#0f1419", fg = "#8ed8c4", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_hint_replace", { bg = "#0f1419", fg = "#8ed8c4", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_hint_terminal", { bg = "#0f1419", fg = "#8ed8c4", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_hint_visual", { bg = "#0f1419", fg = "#8ed8c4", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_info_command", { bg = "#0f1419", fg = "#aec7fc", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_info_inactive", { bg = "#0f1419", fg = "#aec7fc", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_info_insert", { bg = "#0f1419", fg = "#aec7fc", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_info_normal", { bg = "#0f1419", fg = "#aec7fc", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_info_replace", { bg = "#0f1419", fg = "#aec7fc", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_info_terminal", { bg = "#0f1419", fg = "#aec7fc", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_info_visual", { bg = "#0f1419", fg = "#aec7fc", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_warn_command", { bg = "#0f1419", fg = "#dfc48b", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_warn_inactive", { bg = "#0f1419", fg = "#dfc48b", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_warn_insert", { bg = "#0f1419", fg = "#dfc48b", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_warn_normal", { bg = "#0f1419", fg = "#dfc48b", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_warn_replace", { bg = "#0f1419", fg = "#dfc48b", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_warn_terminal", { bg = "#0f1419", fg = "#dfc48b", nocombine = true })
hi(0, "lualine_x_fancy_diagnostics_warn_visual", { bg = "#0f1419", fg = "#dfc48b", nocombine = true })
hi(0, "lualine_x_fancy_location_command", { bg = "#0f1419", fg = "#fc5603", nocombine = true })
hi(0, "lualine_x_fancy_location_inactive", { bg = "#0f1419", fg = "#fc5603", nocombine = true })
hi(0, "lualine_x_fancy_location_insert", { bg = "#0f1419", fg = "#fc5603", nocombine = true })
hi(0, "lualine_x_fancy_location_normal", { bg = "#0f1419", fg = "#fc5603", nocombine = true })
hi(0, "lualine_x_fancy_location_replace", { bg = "#0f1419", fg = "#fc5603", nocombine = true })
hi(0, "lualine_x_fancy_location_terminal", { bg = "#0f1419", fg = "#fc5603", nocombine = true })
hi(0, "lualine_x_fancy_location_visual", { bg = "#0f1419", fg = "#fc5603", nocombine = true })
hi(0, "lualine_x_fancy_macro_command", { bg = "#0f1419", fg = "#ff0000", nocombine = true })
hi(0, "lualine_x_fancy_macro_inactive", { bg = "#0f1419", fg = "#ff0000", nocombine = true })
hi(0, "lualine_x_fancy_macro_insert", { bg = "#0f1419", fg = "#ff0000", nocombine = true })
hi(0, "lualine_x_fancy_macro_normal", { bg = "#0f1419", fg = "#ff0000", nocombine = true })
hi(0, "lualine_x_fancy_macro_replace", { bg = "#0f1419", fg = "#ff0000", nocombine = true })
hi(0, "lualine_x_fancy_macro_terminal", { bg = "#0f1419", fg = "#ff0000", nocombine = true })
hi(0, "lualine_x_fancy_macro_visual", { bg = "#0f1419", fg = "#ff0000", nocombine = true })
hi(0, "lualine_x_fancy_searchcount_command", { bg = "#0f1419", fg = "#fcba03", nocombine = true })
hi(0, "lualine_x_fancy_searchcount_inactive", { bg = "#0f1419", fg = "#fcba03", nocombine = true })
hi(0, "lualine_x_fancy_searchcount_insert", { bg = "#0f1419", fg = "#fcba03", nocombine = true })
hi(0, "lualine_x_fancy_searchcount_normal", { bg = "#0f1419", fg = "#fcba03", nocombine = true })
hi(0, "lualine_x_fancy_searchcount_replace", { bg = "#0f1419", fg = "#fcba03", nocombine = true })
hi(0, "lualine_x_fancy_searchcount_terminal", { bg = "#0f1419", fg = "#fcba03", nocombine = true })
hi(0, "lualine_x_fancy_searchcount_visual", { bg = "#0f1419", fg = "#fcba03", nocombine = true })
hi(0, "lualine_y_fancy_filetype_DevIconLua_command", { bg = "#14191f", fg = "#51a0cf", nocombine = true })
hi(0, "lualine_y_fancy_filetype_DevIconLua_inactive", { bg = "#14191f", fg = "#51a0cf", nocombine = true })
hi(0, "lualine_y_fancy_filetype_DevIconLua_insert", { bg = "#14191f", fg = "#51a0cf", nocombine = true })
hi(0, "lualine_y_fancy_filetype_DevIconLua_normal", { bg = "#14191f", fg = "#51a0cf", nocombine = true })
hi(0, "lualine_y_fancy_filetype_DevIconLua_replace", { bg = "#14191f", fg = "#51a0cf", nocombine = true })
hi(0, "lualine_y_fancy_filetype_DevIconLua_terminal", { bg = "#14191f", fg = "#51a0cf", nocombine = true })
hi(0, "lualine_y_fancy_filetype_DevIconLua_visual", { bg = "#14191f", fg = "#51a0cf", nocombine = true })
hi(0, "lualine_y_fancy_filetype_ts_icon_command", { bg = "#14191f", fg = "#41942c", nocombine = true })
hi(0, "lualine_y_fancy_filetype_ts_icon_inactive", { bg = "#14191f", fg = "#41942c", nocombine = true })
hi(0, "lualine_y_fancy_filetype_ts_icon_insert", { bg = "#14191f", fg = "#41942c", nocombine = true })
hi(0, "lualine_y_fancy_filetype_ts_icon_normal", { bg = "#14191f", fg = "#41942c", nocombine = true })
hi(0, "lualine_y_fancy_filetype_ts_icon_replace", { bg = "#14191f", fg = "#41942c", nocombine = true })
hi(0, "lualine_y_fancy_filetype_ts_icon_terminal", { bg = "#14191f", fg = "#41942c", nocombine = true })
hi(0, "lualine_y_fancy_filetype_ts_icon_visual", { bg = "#14191f", fg = "#41942c", nocombine = true })
hi(0, "markdownH1", { link = "@markup.heading.1" })
hi(0, "markdownH2", { link = "@markup.heading.2" })
hi(0, "markdownH3", { link = "@markup.heading.3" })
hi(0, "markdownH4", { link = "@markup.heading.4" })
hi(0, "markdownH5", { link = "@markup.heading.5" })
hi(0, "markdownH6", { link = "@markup.heading.6" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#001314"
g.terminal_color_1 = "#f2b2c9"
g.terminal_color_2 = "#b5d29b"
g.terminal_color_3 = "#dfc48b"
g.terminal_color_4 = "#8ad4eb"
g.terminal_color_5 = "#d7b9ee"
g.terminal_color_6 = "#8ed8c4"
g.terminal_color_7 = "#868e8e"
g.terminal_color_8 = "#435c5d"
g.terminal_color_9 = "#f2b2c9"
g.terminal_color_10 = "#b5d29b"
g.terminal_color_11 = "#dfc48b"
g.terminal_color_12 = "#8ad4eb"
g.terminal_color_13 = "#d7b9ee"
g.terminal_color_14 = "#8ed8c4"
g.terminal_color_15 = "#e5eeee"
