-- You can add your own plugins here or in other files in this directory!
--  I promise not to create any merge conflicts in this directory :)
--
-- See the kickstart.nvim README for more information
return {
  -- Neotree Plugin
  -- Neo-tree is a Neovim plugin to browse the file system and other tree like structures in whatever style suits you,
  -- including sidebars, floating windows, netrw split style, or all of them at once!
  -- {
  --   'nvim-neo-tree/neo-tree.nvim',
  --   branch = 'v3.x',
  --   dependencies = {
  --     'nvim-lua/plenary.nvim',
  --     'nvim-tree/nvim-web-devicons', -- not strictly required, but recommended
  --     'MunifTanjim/nui.nvim',
  --     -- "3rd/image.nvim", -- Optional image support in preview window: See `# Preview Mode` for more information
  --   },
  --   config = {
  --     require('neo-tree').setup {
  --       close_if_last_window = true,
  --     },
  --   },
  -- },
}
